version: "3.9"
services: 
    server: 
        container_name: "server"
        build: ./
        ports: 
            - "4200:4200"
        depends_on: 
            - mongodb
            - elastic
        restart: always
        links:
            - mongodb
            - elastic
        env_file: ./production.env

    mongodb: 
        container_name: "mongodb"
        image: mongo:4.4.7-focal
        restart: always
        volumes: 
            - mongodb:/data/db
        ports: 
            - "27017:27017"

    elastic: 
        container_name: "elastic"
        image: elasticsearch:7.13.4
        restart: always
        environment: 
            discovery.type: single-node
            cluster.name: elastic-crm
        ports: 
            - "9200:9200"
            - "9300:9300"
        deploy:
            resources: 
                limits:
                    cpus: '0.50'
                    memory: 500M
                reservations:
                    cpus: '0.25'
                    memory: 150M
        volumes: 
            - elastic:/usr/share/elasticsearch/data
volumes: 
    mongodb:  
    elastic:
