version: "3.9"
services:
    backend:
        build: ./
        ports:
            - "4200:4200"
        depends_on:
            - mongodb
            - elastic
        restart: always
        links:
            - mongodb
            - elastic
        env_file: .env

    mongodb:
        image: mongo:4.4.7-focal
        restart: always
        volumes:
            - mongodb:/data/db
        ports:
            - "27017:27017"
        env_file: mongodb.env

    elastic:
        image: elasticsearch:7.13.4
        restart: always
        environment:
            - discovery.type=single-node
            - cluster.name=elastic-crm
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            - ELASTIC_USERNAME=$ELASTIC_USERNAME
            - xpack.security.enabled=$ELASTIC_SECURITY
        ports:
            - "9200:9200"
        volumes:
            - elastic:/usr/share/elasticsearch/data
        env_file: elastic.env

volumes:
    mongodb:
    elastic: