[build.environment]
    NODE_ENV = "development"
    ELASTIC_SEARCH_URI = "https://hdf569ko0k:t6luw1szqo@crm-5690317700.us-east-1.bonsaisearch.net:443"

[build]
    base = "./server/"
    command = "yarn build && yarn start:prod"