export enum ActionRights {
    CREATE_STUDENT = 'crm:student:create',
    EDIT_STUDENT = 'crm:student:update',
    DELETE_STUDENT = 'crm:student:delete',
    SEE_STUDENT = 'crm:student:read',
    CREATE_STUDENT_NOTE = 'crm:student:notes:create',
    EDIT_STUDENT_NOTE = 'crm:student:notes:update',
    DELETE_STUDENT_NOTE = 'crm:student:notes:delete',
    IMPORT_STUDENTS_VIA_FILE = 'crm:student:import',
    CREATE_STUDENT_STATUS = 'crm:student:statuses:create',
    SEE_STUDENT_STATUSES = 'crm:student:statuses:read',
    EDIT_STUDENT_STATUS = 'crm:student:statuses:update',
    DELETE_STUDENT_STATUS = 'crm:student:statuses:delete',
    CREATE_GROUP = 'crm:group:create',
    EDIT_GROUP = 'crm:group:update',
    DELETE_GROUP = 'crm:group:delete',
    MANAGE_GROUP_STUDENTS = 'crm:group:students:manage',
    SEE_GROUP = 'crm:group:read',
    USE_SEARCH = 'crm:search:read',
    CREATE_TASK = 'crm:tasks:create',
    EDIT_TASK = 'crm:tasks:update',
    DELETE_TASK = 'crm:tasks:delete',
    SEE_TASK = 'crm:tasks:read',
    CREATE_TASK_TAG = 'crm:tasks:tags:create',
    SEE_TASK_TAG = 'crm:tasks:tags:read',
    EDIT_TASK_TAG = 'crm:tasks:tags:update',
    DELETE_TASK_TAG = 'crm:tasks:tags:delete'
}
