export enum DataRights {
    CAN_SEE_STUDENT_NAME = 'student:name',
    CAN_SEE_STUDENT_SURNAME = 'student:surname',
    CAN_SEE_STUDENT_MIDDLE_NAME = 'student:middle_name',
    CAN_SEE_STUDENT_GENDER = 'student:gender',
    CAN_SEE_STUDENT_DATE_OF_BIRTH = 'student:date_of_birth',
    CAN_SEE_STUDENT_PHONE = 'student:phone',
    CAN_SEE_STUDENT_PARENT_PHONE = 'student:parent_phone',
    CAN_SEE_STUDENT_PARENT_FULL_NAME = 'student:parent_full_name',
    CAN_SEE_STUDENT_BALANCE = 'student:balance',
    CAN_SEE_STUDENT_DISCORD = 'student:discord',
    CAN_SEE_STUDENT_SALES_FUNNEL_STEP = 'student:sales_funnel_step',
    CAN_SEE_STUDENT_STATUSES = 'student:statuses',
    CAN_SEE_STUDENT_NOTES = 'student:notes',
    CAN_SEE_STUDENT_GROUPS = 'student:groups',
    CAN_SEE_STUDENT_TUTORS = 'student:tutors',
    CAN_SEE_GROUP_NAME = 'group:group_name',
    CAN_SEE_GROUP_LEVEL = 'group:level',
    CAN_SEE_GROUP_PLACES = 'group:places',
    CAN_SEE_GROUP_STUDENTS = 'group:students',
    CAN_SEE_GROUP_TUTOR = 'group:tutor'
}
